### PR TITLE
add build target for windows

### PR DESCRIPTION
**Pull request by ystyle**

### CODE REVIEW

**Comment by varbhat** [comment]
@ystyle ,

I have built for windows using mingw (exactly what you have done. I have even tried it ten times yesterday) . But, it didn't run on windows and showed libstdc++ dll errors and few other errors that i couldn't resolve. 

someone built and cross compiled successfully from debian though.

So, since there is uncertainty whether this runs properly, i am not merging this pull request ( i will try again with windows vm too in future)

**Comment by ystyle** [comment]
Yesterday when I was at home, I compiled it on the linux server remotely. After the compilation is successful, it can be executed locally, and the user can be added and the megnet link can be downloaded correctly.
The compilation environment is: `ghcr.io/varbhat/void-container:musl`

**Comment by ystyle** [comment]
Or add a job to github actions and use ghcr.io/varbhat/void-container:musl to compile

**Comment by varbhat** [comment]
@ystyle ,

Did you have mingw installed locally in windows too?

Also, thanks for reporting . I want to check cross compiled binary once on windows and will proceed.

**Comment by ystyle** [comment]
> @ystyle ,
> 
> Did you have mingw installed locally in windows too?
> 
> Also, thanks for reporting . I want to check cross compiled binary once on windows and will proceed.

@varbhat 

No, I compiled it with `ghcr.io/varbhat/void-container:musl` on the remote server with docker, and installed `cross-x86_64-w64-mingw32` in it

**Pull request closed without merging**
