### PR TITLE
trigger build on every push 

### PR DESCRIPTION
**Pull request by evrins**
trigger build on every push to make sure every commit can compile successfully
it will **only** push docker image with tag `latest` on tagged push 
but it will consume more github action minutes, it may cost money or disabled if exceed [free usage limit](https://docs.github.com/en/get-started/learning-about-github/githubs-plans#github-free-for-personal-accounts)

### CODE REVIEW

**Comment by nlevee** [comment]
Hi,
Thank you for your contribution, please can you split your PR to separate golang upgrade ?

@varbhat do you want this feature ? I think we can merge and see.

**Comment by evrins** [comment]
yes
i can create another pr fix miss matched  golang version with go.mod
golang upgrade in this pr is a fix, or the workflow will not work

**Comment by varbhat** [comment]
@evrins @nlevee 

Do we really need this feature?

I had always assumed that anything pushed to this repo must always compile (only push it if make build is successful). that's the reason i didn't add this in first place.

Feel free to discuss. if this is really free, it might be worthy but sometimes i do think it might be wastage of computer cycles. Maybe this might be beneficial to see if it breaks on other platforms if there's some breakage in underlying library.

**Comment by evrins** [comment]
it is about 2000 github action minutes per month in my free limit  and action run cost abount 50 github action minutes

may be we can trigger on pr to reduce action runs

I think it is necessary to check build somewhere to fix some works-well-on-my-computer issue
also it can prevent from others breaking build by accident

**Comment by nlevee** [comment]
I think it's a good practice to test at every stage, we ça activate it on every commit in PR, and on every commit on main. 

If the number of PR rise too much we can deactivate it on PR commit later. 

So @nlevee can you change the rules if @varbhat is ok with this ? And we can merge then

**Comment by varbhat** [comment]
Go Ahead. 

ACK from my side.

**Comment by evrins** [comment]
have changed rule to run pull_request open / reopen / synchronize (commit push on pull request branch)
and on every commit on main branch 
@nlevee @varbhat

**Review by nlevee — APPROVED** [review]

**Pull request merged**
