### PR TITLE
Expose web UI port

### PR DESCRIPTION
**Pull request by agneevX**

### CODE REVIEW

**Comment by varbhat** [comment]
@agneevX , i intentionally didn't expose it because there might be users who map the guest port to different host port.

also, you need to bind other "torrent" port.

**Comment by agneevX** [comment]
I created this PR so service discovery applications can automatically discover the web UI port. 

> there might be users who map the guest port to different host port.

I'm not sure what this means. 

> also, you need to bind other "torrent" port.

This was not done as the user can bind the connection ports to their choice.

**Comment by varbhat** [comment]
Thanks @agneevX for your contribution. I have merged the PR.

**Comment by agneevX** [comment]
Thanks @varbhat!

**Pull request merged**
