### PR TITLE
Makefile change to allow building on macOS

### PR DESCRIPTION
**Pull request by bsergean**
When using the Linux build options the build fail with

```
/usr/local/go/pkg/tool/darwin_amd64/link: running clang++ failed: exit status 1
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [app] Error 2
```

### CODE REVIEW

**Comment by varbhat** [comment]
@bsergean ,

I think `-static` flag is issue. We could have other flags as it is on MacOS instead of removing every flag.

What do you think?

**Comment by varbhat** [comment]
@bsergean ,

Also thanks for confirming that exatorrent compiles and runs on MacOS . I want to use github actions to also release for MacOS in future.

**Comment by bsergean** [comment]
You're right it's just the -static flag that make it fails to build on osx. I don't know if -piemode makes a difference on osx, but it doesn't hurt.

**Comment by bsergean** [comment]
Updated the makefile bit.

Ps: totally unrelated, but do you know if exatorrent has code to seed a local file (without downloading it first) ?
https://github.com/anacrolix/torrent/discussions/556

**Comment by varbhat** [comment]
@bsergean ,

currently No but please take a look at this : https://github.com/anacrolix/torrent/blob/master/cmd/torrent-create/main.go

**Comment by bsergean** [comment]
Yes I know about this link, thanks for sharing / I know how to create the torrent, but then I don't know what to do with it. I can set the announce list to a tracker I know of. I think I'm really close but I can't make it work.

What I need is torrent client that sticks around and acts as the Seeder, but I don't know what api to use.

I'm trying to setup a unittest to test downloads, no success yet -> https://github.com/bsergean/torrent_download

**Comment by varbhat** [comment]
@bsergean ,

Please see https://github.com/varbhat/exatorrent/commit/cc3afc8a38a27c432ade648790ccd7e17eecb1d9 .

I have added `app-no-sl` make commands .  Mainly , I avoided `if` condition because even when compiling in termux , only `static` flag needs to be avoided , so added seperate `app-no-sl` instead .

Also , I have successfully cross-compiled exatorrent using osxcross , so expect some progress regarding that :)

**Comment by bsergean** [comment]
Perfect. Good that you found a way.

**Pull request closed without merging**
